# Getting started

## Modules

In [1]:
import os
from pyfileindex import PyFileIndex

## User defined functions

In [2]:
def touch(fname, times=None):
    with open(fname, "a"):
        os.utime(fname, times)

In [3]:
def filter_function(file_name):
    return ".txt" in file_name

# Demonstrate PyFileIndex

## Initialise PyFileIndex

In [4]:
pfi = PyFileIndex(path=".", filter_function=filter_function, watch=True, debug=True)
pfi

## Update PyFileIndex

In [5]:
pfi.update()
pfi

## New directory

In [6]:
os.makedirs("bla")

In [7]:
pfi.update()
pfi

Changes:  ['/home/jovyan/notebooks/bla'] []

## New sub directory

In [8]:
os.makedirs("bla/bla")

In [9]:
pfi.update()
pfi

Changes:  ['/home/jovyan/notebooks/bla/bla'] []

## New file

In [10]:
touch("bla/bla/test.txt")

In [11]:
pfi.update()
pfi

Changes:  ['/home/jovyan/notebooks/bla/bla/test.txt'] []

## Another new file

In [12]:
touch("bla/test.txt")

In [13]:
pfi.update()
pfi

Changes:  ['/home/jovyan/notebooks/bla/test.txt'] []

## Touch an existing file

In [14]:
touch("bla/bla/test.txt", (1330712280, 1330712292))

In [15]:
pfi.update()
pfi

Changes:  ['/home/jovyan/notebooks/bla/bla/test.txt'] []

## Remove a file

In [16]:
os.remove("bla/bla/test.txt")

In [17]:
pfi.update()
pfi

Changes:  [] ['/home/jovyan/notebooks/bla/bla/test.txt']

## Remove a directory

In [18]:
os.rmdir("bla/bla")

In [19]:
pfi.update()
pfi

Changes:  [] ['/home/jovyan/notebooks/bla/bla']

## Clean up

In [20]:
os.remove("bla/test.txt")

In [21]:
os.rmdir("bla")

In [22]:
pfi.update()
pfi

Changes:  [] ['/home/jovyan/notebooks/bla/test.txt', '/home/jovyan/notebooks/bla']